# Font
#######################################

[font]
size = 13

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.italic]
family = "FiraCode Nerd Font"
style = "Regular Italic"

[font.bold]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

# Keybindings
#######################################

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"
[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"
[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"
[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"
[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

# Mouse
#######################################

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mods = "None"
mouse = "Right"
action = "Paste"

[selection]
save_to_clipboard = true

# Other
#######################################

[scrolling]
history = 5000

[shell]
program = "ubuntu.exe"

[window]
# centers padding area:
dynamic_padding = true
decorations = "full"
opacity = 0.85
