# Font
#######################################

[font]
# in points:
size = 13

[font.offset]
y = 4
[font.glyph_offset]
y = 2

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

# Keybindings
#######################################

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

# Mouse
#######################################

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mods = "None"
mouse = "Middle"
action = "Paste"

[selection]
save_to_clipboard = true

# Other
#######################################

[scrolling]
history = 5000

[shell]
program = "ubuntu.exe"

[window]
# centers everything when not multiple of char size
# makes the UI look less "off":
dynamic_padding = true
decorations = "full"
opacity = 1.0
