theme = "ayu_evolve"

[editor]
mouse = true
undercurl = true
true-color = true
line-number = "relative"
color-modes = true # color mode indicator differently per mode
auto-save = false # when moving away from terminal
auto-format = true # formatting on save, sets this generally for all LSPs
preview-completion-insert = true # apply completion item when selected
auto-completion = true # automatic popup of auto-completion, else ctrl+x
completion-trigger-len = 1 # default 2, 0 immediately shows suggestions
auto-info = true
auto-pairs = true
bufferline = "multiple" # show tabs when there is more than one open
rulers = [80, 100]
text-width = 80 # for :reflow and soft-wrap.wrap-at-text-width

[editor.soft-wrap]
enable = true
# wrap-at-text-width = true

[editor.lsp]
enable = true
display-messages = true # lsp progress msgs below statusline
auto-signature-help = true # automatic popup of parameter hints
display-inlay-hints = false # still being improved on, use space-i to toggle
display-signature-help-docs = true # docs under signature help popup
snippets = true # enable snippet completions, requires :lsp-restart
goto-reference-include-declaration = true # include declaration in goto refs

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false # show hidden files

[editor.statusline]
left = [
  "mode", "spinner", "diagnostics", "workspace-diagnostics", "file-name",
  "file-modification-indicator", "version-control"
]
center = []
right = ["selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.indent-guides]
render = true
# skip-levels = 1

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
X = ["extend_line_up", "extend_to_line_bounds"] # the reverse of x

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
q = ":q"
x = ":bc"
"," = ":w"
"!" = ":q!"
o = ":reload-all"

[keys.insert]
C-space = "signature_help"

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
C-j = [
  'ensure_selections_forward',
  'extend_to_line_bounds',
  'extend_char_right',
  'extend_char_left',
  'delete_selection','add_newline_below',
  'move_line_down',
  'replace_with_yanked',
]
C-k = [
  'ensure_selections_forward',
  'extend_to_line_bounds',
  'extend_char_right',
  'extend_char_left',
  'delete_selection',
  'move_line_up',
  'add_newline_above',
  'move_line_up',
  'replace_with_yanked',
]
